# NOTE: This file must be encrypted with SOPS before committing.
# Run: sops --encrypt --in-place kubernetes/main/cluster/cluster-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5w6OO+y5bwXjevD/tUE=,iv:G3V0yaHPe/YSdUQtXbQi5AAJkZaHMedY0qBAM70Vj7w=,tag:URZ0duXbFGNre8i6Gm4TbQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dc7AfP3/YTdybAVT6GigdcuUAQ==,iv:7DBaxko/HvYpHz4H9V8aT9fgeOIQav3Atrq+TZkJ7hE=,tag:NREQxRtbXlbF/xuHAu5/jg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jLtxFeJIyX3qyJlPcp1Aw5oMwLAObGBevhxtRDdj1gO1/KJo,iv:ouO4DgyCRBetl7YDLqMGK5Uwjl/aNeXkGHiQ5t0c3wY=,tag:HWmYfj5gWah434/f2u8XHQ==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOHU0akpGOXN4ajBTTGh5
            R1pzSm9YaEI0NHNCSzg1YkNiWFhuT1ZETFhZCmNLbUlyY1poRTVLVlpGaFZLNUQ0
            SURCc2M0WG1tc2xQQkZoTklkeEJISHMKLS0tIEpCakNUcllrR1ROWDNhRnhXTzAv
            NVp1Kzg2Y1l1QUxkWHpybjhKOGdyMUkK82wovSfCs2pEAmXVK6A6p33weSQSM7sD
            foEWFd/B6Aq4B5M6aX75TabXrQmcDIjgwFsfmWOIiURc3iopstdmDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T10:54:33Z"
    mac: ENC[AES256_GCM,data:aJ1AFhEbWKwX7W4MBd8R8Uok/Gb+90xJ72o+zjv/iXQf0zNnyeVV+HGyd6k4rveIdasQT7zFCk7M5m7GdR8f1V7udv2LPvyyFG0NS4MrP0QT9t5dwPzks86MVB0atyclwkMhqUIsHPL36JxW8eRnw2utQ0MG9U5jfFT2u4Bmq4I=,iv:RRraSsY0Qd6bl8clwVQOxRDGp2MSY+q4IhsMV8Q+ZtM=,tag:Cs0QqmkI01sWhOYkv9VuoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
