---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unifi-exporter
  namespace: observability
spec:
  jobLabel: unifi-exporter
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
