---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unifi-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: unifi-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
