apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
    namespace: observability
type: Opaque
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:Ixgc,iv:UlxSIlWllWypW2rejstDPscobjZRB0s520aEAKXRgLk=,tag:gYnOyJDJys3Dvxc1ZaABUA==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:C5yAPIlFwVzC9ua+/DGEPu78bu1jRp9qMh/fekEgopo=,iv:9l3t18o9G3p8phtWPskYM9ETJL2RKObjItRy9xkNevA=,tag:iXzKoFNHYCTDKUfW2990+A==,type:str]
    UP_UNIFI_DEFAULT_VERIFY_SSL: ENC[AES256_GCM,data:+EV2NT8=,iv:XKsOI+Ct/b889b0J/Jd1XX6Ili+ewkETJdzsFNAN5ko=,tag:e2buOsVp+eJSL5a3+PL20A==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dHF6Zkw1bXAxdWJrbVV0
            Sk1BN3dTbmVQeGkrL2pxWUI5ZjIwUlFwWkhNCmlZYWJTNitPNGdXL2ErZUovTUYx
            Qkc3N1dIM3lCQnBxNVkvbUFjSnRjMlUKLS0tIEZzdVAxd3Q4L0NMMUdzWEpiNUtE
            UjVKREx0SWY3U1FseFU2YzJGRDlKWEEKmjCLotQCmoHL01q3HyxYLA0KIdz9KGhK
            RPQAYrWa8WIpxP34traTSfcmsPIKW5PTBztoEq98Kb2wuWOzAwRHEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T11:48:48Z"
    mac: ENC[AES256_GCM,data:kVVi6AhwCTj7ITd0XKs7QkYPWR8boPUJ+vuQOufMBHH1ARgOn0vCIHPJSg3kIjJEcxCD9xa0yScNTMTYwbqd6QE48UoXg8B0lG+HZjCCdsiEoFcnLHvfzR2k2KyAD8g6L71YZpuhHxaD3I2dueS37avhhEmK073Bra/5rzl0rNA=,iv:LJ7Hq22TAKcab4hkHFS9dS9QbsBKwZcwNFA8Xx067sk=,tag:WgqK54wwpjqj5PT5ddB58g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
