apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:GVCKBmotgM8thKdkwAoObudUfZVAO6nz4SXFFXwk32c=,iv:H/pdjyZiPwzOXuX0K0nVKJ2qj9eg1Ka4wWdVGodet24=,tag:Ct2mElWO52byc73wCs8C9w==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS2xuT3ZMUzR0WFpnd3gw
            RzRlNzE5b0pINUswL2pmU01lb2lrdzJyT3pFCkxIYm5PdzVVakw2SlFCMU9vZEd1
            MnV4T1ZQeDZVTURMaGlRaTZOYlFmeU0KLS0tIEtVOTR5UHRoek5USC9CRlFwRnFz
            WElDNTh3K2srd29MT1VmYWVFVHo1eTQK9Ex/czOKIxkDUJ3ly7cO4RmN9W70xzbu
            7hOGE53UTmjeUi5mtjhgsy+tDhHrXjOI6MwKUfK/KElqU3ZW41M8aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T10:54:42Z"
    mac: ENC[AES256_GCM,data:HxKNXJSGvGz5Gats1YHeQQhiuWYobXdsE5b1Ba9yuHfIa3ALKNSGNIrV0436TO3C+/aOYCU1KF9RhLbR6UJSHPTvB3U3E0NJx+bw3XOe/io5EmU0kAA3WgpzSGQpvSnEXX/zj64IWQQBbFPR62qIGiIONhadcBBP93mV8JkBmbg=,iv:2ERjoKPL+0Sy5v9BCphhmWVLR7QtohVQj7nj/qNAHnk=,tag:0bO2290PGo/ppQ98Z1nxCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
