---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-infinity.yaml
  - ./configmap-infinity-datasource.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-dashboard-energy-pv
    namespace: observability
    files:
      - energy-pv.json=./dashboards/energy-pv.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Energy
  - name: grafana-dashboard-energy-pv-v2
    namespace: observability
    files:
      - energy-pv-v2.json=./dashboards/energy-pv-v2.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Energy
