---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-health-data
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-ceph-filesystem
  resources:
    requests:
      storage: 5Gi
