---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app it-tools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      it-tools:
        containers:
          app:
            image:
              repository: ghcr.io/corentinth/it-tools
              tag: 2024.5.13-a0bc346
            env:
              TZ: "Europe/Amsterdam"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 500Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    route:
      main:
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        hostnames:
          - "it-tools.${SECRET_DOMAIN}"
