apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:EMQ2fwXpCvXLw4GoE4E1Anp8EaWM5/WM/36FYZM9K7DcTAfc28x56Q==,iv:dY6YrkU3htxkhBweLDByht3+raFItSDPBl8503R8cLo=,tag:pEJ7m5ifPVsgr51ZzK4gzw==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZXdXZnVYT0UvWG5KMzBO
            WDYwTVoxTG5LdndkdXlnakpFMzFOaTRnaVEwClZ4S2czc0tETVByalpjM2ZqSGk3
            OHFxcDV6TmQ5eHZCUk8vZzdSWFhJeDgKLS0tIEdDZ0VQTGN3MjRjVUNDSjkwQ3U3
            VDhkVStqNndMRU5sV1dHYTlTczJ5a28K2u9dceeiPfkC9PkYfUABOE/TxWkSPNAU
            gflON5XGOISN1aWmPIqrafV+5qloFTUko4L7YFh/Zjd0gtzAZCmVSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T10:54:40Z"
    mac: ENC[AES256_GCM,data:mk9uyZWaF0g+pzHxXdS4SJ8DnP4n2zqQ8dwjSfVZuRTQOi4Zir62pYNk0WbCeYVh1YdJ9s1nwuxBgQ/k/m6GfAycD1Ih3pTlUnGXzfXKbRVg6gjDeTGhpp1poe22rTDJs7cZzhiSDlppgpAfYo69DeNMkn1BoFykYYlIkcnNVfc=,iv:yYljmMEcC+8MpmJlj/3gy0/zgYkhm18/b5so/JBvgNo=,tag:/RzwqWmpyMC6cUFs86FRsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
