apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ksWxdtF7TdFMX9nBz5g1idWMo46/dMXrhi9VVJTrrqPg+zcyLosYIg==,iv:dQEW+z+nVtqjwyx+pSBVw4tnJ8VjGNTf15p/5OBCFbE=,tag:JpvECiIpdjqzxYhZdjRhAg==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTUY0dFVYMUU3TDVSUU82
            RHNkRTBIOXFRT29EQUtMSnYrNk9MelFOMGlzCko3NUJCOEVIY1VhSSt6eFJpYW1T
            YmNaK0h1ZXlrbTNJWHViMVEzWUIxeEEKLS0tIGxSZW52bEFwTW1ET2JFRGFJUWkz
            QlFtVk5VQVR4dDU0Ri9SQjVZb09SYk0KwTqG+PQfroxgBAIdjggqedJp8Y8c4E91
            BOGNPum1u/7R3V+Dt+xZNFwEv7m3/haNC87RX6tjIgED57f9UI1Tjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T10:54:39Z"
    mac: ENC[AES256_GCM,data:QT7GCdvgsLLawclHpWeVQ6JEgGoDbj6i9mhxR9i7rSV4Utuq/fk4ww6dxcFh5S3xvVVawdcNr2aRwXXdWgN80sgFczCRhOgjeT1Qc/8I42JR9qwk7fh+5JNBiSsEgfqBilHWoIOX8qjwJwRfqpyhw8WEAXYSHC3XRETXJWMG8Fk=,iv:MlVAdcik0eQf7/UPODOdsSDI5HD2fPL3/AZp4C2eP1M=,tag:qYixl7pdVdPq/XxkW83AkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
