---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ceph-smart-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  path: ./kubernetes/main/apps/observability/ceph-smart-exporter/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
