---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mosquitto
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: "{{ .MOSQUITTO_MQTT_USERNAME }}"
        password: "{{ .MOSQUITTO_MQTT_PASSWORD }}"
        mosquitto_pwd: |
          {{ .MOSQUITTO_MQTT_USERNAME }}:{{ .MOSQUITTO_MQTT_PASSWORD }}
  dataFrom:
    - extract:
        key: mosquitto
