---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tesla-public-key
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: tesla-public-key-secret
    template:
      engineVersion: v2
      data:
        com.tesla.3p.public-key.pem: "{{ .TESLA_FLEET_KEY_PUB }}"
  dataFrom:
    - extract:
        key: Tesla
