#!/usr/bin/env python3
"""Push the day's markdown report to docs/health-reports/ in the repo.

Reads the SSH deploy key from /secrets/id_ed25519 (mounted from
cluster-health-secret), shallow clones the repo, copies the report,
updates docs/health-reports/README.md (rolling 30-entry index),
commits, and pushes. Failure is non-fatal — the report still lives on PVC."""
from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, "/scripts")
from lib import REPORTS_DIR, log, run, today  # noqa: E402

GIT_REMOTE = os.environ.get("GIT_REMOTE", "git@github.com:vdhict/vdhinfra.git")
GIT_BRANCH = os.environ.get("GIT_BRANCH", "main")
GIT_NAME = os.environ.get("GIT_AUTHOR_NAME", "cluster-health-bot")
GIT_EMAIL = os.environ.get("GIT_AUTHOR_EMAIL", "cluster-health@bluejungle.net")

SECRET_KEY = Path("/secrets/id_ed25519")
KNOWN_HOSTS = Path("/secrets/known_hosts")


def main() -> int:
    date = today()
    md = REPORTS_DIR / f"{date}.md"
    if not md.exists():
        log(f"git_push: no report {md}")
        return 0
    if not SECRET_KEY.exists():
        log("git_push: no SSH key mounted at /secrets/id_ed25519, skipping")
        return 0

    # SSH config
    ssh_dir = Path(tempfile.mkdtemp(prefix="ssh-"))
    key_path = ssh_dir / "id_ed25519"
    shutil.copy(SECRET_KEY, key_path)
    key_path.chmod(0o600)
    kh_path = ssh_dir / "known_hosts"
    if KNOWN_HOSTS.exists():
        shutil.copy(KNOWN_HOSTS, kh_path)
    else:
        kh_path.write_text("")
    git_ssh = f"ssh -i {key_path} -o UserKnownHostsFile={kh_path} -o StrictHostKeyChecking=yes"
    env = os.environ.copy()
    env["GIT_SSH_COMMAND"] = git_ssh

    work = Path(tempfile.mkdtemp(prefix="repo-"))
    try:
        rc, _, err = _run_env(["git", "clone", "--depth", "1", "--branch", GIT_BRANCH, GIT_REMOTE, str(work)], env)
        if rc != 0:
            log(f"git_push: clone failed: {err.strip()[:300]}")
            return 1

        # Configure author
        _run_env(["git", "-C", str(work), "config", "user.name", GIT_NAME], env)
        _run_env(["git", "-C", str(work), "config", "user.email", GIT_EMAIL], env)

        target_dir = work / "docs" / "health-reports"
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / f"{date}.md"
        shutil.copy(md, target)

        # Refresh index README (most recent 30)
        index = target_dir / "README.md"
        existing = sorted([f for f in target_dir.glob("????-??-??.md")], reverse=True)[:30]
        idx_lines = ["# Daily Health Reports", "",
                     "Auto-generated by the `cluster-health` CronJob in the `observability` namespace.",
                     "",
                     "| Date | Report |",
                     "|---|---|"]
        for f in existing:
            d = f.stem
            idx_lines.append(f"| {d} | [{d}.md]({d}.md) |")
        idx_lines.append("")
        index.write_text("\n".join(idx_lines))

        # Commit
        rc, st, _ = _run_env(["git", "-C", str(work), "status", "--porcelain"], env)
        if not st.strip():
            log("git_push: nothing to commit")
            return 0
        _run_env(["git", "-C", str(work), "add", "docs/health-reports/"], env)
        rc, _, err = _run_env(
            ["git", "-C", str(work), "commit", "-m", f"chore(health): daily report {date}"], env)
        if rc != 0:
            log(f"git_push: commit failed: {err.strip()[:300]}")
            return 1
        rc, _, err = _run_env(["git", "-C", str(work), "push", "origin", GIT_BRANCH], env)
        if rc != 0:
            log(f"git_push: push failed: {err.strip()[:300]}")
            return 1
        log(f"git_push: pushed {date}.md")
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)
        shutil.rmtree(ssh_dir, ignore_errors=True)


def _run_env(args, env):
    import subprocess
    try:
        p = subprocess.run(args, capture_output=True, text=True, env=env, timeout=120)
        return p.returncode, p.stdout, p.stderr
    except Exception as e:  # noqa: BLE001
        return 1, "", str(e)


if __name__ == "__main__":
    sys.exit(main())
