---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .username }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pgadmin
