---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
stringData:
  alertmanager.yaml: |
    route:
      receiver: "null"
      group_by: ["alertname", "severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - matchers:
            - severity = critical
          receiver: ha-critical
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
    receivers:
      - name: "null"
      - name: ha-critical
        webhook_configs:
          - url: http://home-assistant.home-automation.svc.cluster.local:8123/api/webhook/alertmanager-critical
            send_resolved: true
