machine:
  kubelet:
    extraArgs:
      rotate-server-certificates: "true"
    extraConfig:
      serializeImagePulls: false
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options:
          - bind
          - rshared
          - rw
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 172.16.2.0/23
    disableManifestsDirectory: true
