apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vYA4FNEJShZWChxNjZVpgzqLRWau/a+ZlCSlk3O7A5+p195L,iv:Nhj9xDWzE9Z4GP7HLtOxGfRYzzSFCdf89Ck63TsUu98=,tag:cNo4LwqLogrbdywBoHrnYg==,type:str]
    credentials.json: ENC[AES256_GCM,data:S91TdaB0xvVmUL79+FWTXh4yxAjXH/c3qz7wfKS/NbvE14rNMd5viIp16+vjfRjretYwu1/4wfLtcB186P4/L40mMTeU9DhBWkH9qsjT73lhAEe6Emd/l2XsL/pFSqt3UP91DKMSHlhAjlUc2usUK4+y1V1oSocAQCLoJchxfFwSLY+/7aB9RPlBbMg1Z+phFVVxSn0KM0qXi4ldm/DK5W3f,iv:5WqD8wd6+jXZ2CtY0RfYRc9SXgA77dnn92Zq+z/vE5Q=,tag:ByIN3IlouXVf4sbosNEFWQ==,type:str]
sops:
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMDVmd3dVNDdxVmxrd1lq
            QVlkOW0yejJyTmYzOGMzMmxSVkVxY1VmdXk4Ckpuc2YxRDlzYlR2dHVEVEpvWCsw
            Y3FPOFFlbmx5UGxEQ0U0d0ZwZ1JPcVUKLS0tIG1tblIzZ1RwUmtnQ0hQbDhTRHhK
            Z3BNMFQ3UDVQcm9RQ2tFbDJCYzhZVEUKBa4+CF2IGh2GZ2xFPnpWSAWP9rvkBEHe
            /+EXZICoXdTcJyQwqdVdVfzsTSo4YjgKlJFGP1wH4kL9CvUcGKvCqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T10:54:37Z"
    mac: ENC[AES256_GCM,data:tgYAA+YrF2pRpYRbGnYnCRP+/0zXhJqXT35frzjkZ+J87SpNTCejqKxHhKHDkzt+CgFLml6v0JSmNdMAWRJyg+hU/3lHcQAxegIOXUlsbbavGmvJoopsOKTgzRAiPqNfpXNzFDyg20d84Oi+Vj9VhRGaAtOQtDEfXD2HIrPmGw8=,iv:jAl1S1tzLlsQ6TFFS2hhiUKaUcuATchEyaJ925pv8+s=,tag:rb7+WDHSmVbp9F+C99sVhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
