---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-operator/install.yaml
  - ./flux-instance/install.yaml
  - ./weave-gitops/install.yaml
  - ./webhooks/install.yaml
