---
apiVersion: v1
kind: Service
metadata:
  name: kennisdienst
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kennisdienst
  ports:
    - name: http
      port: 8088
      targetPort: http
