---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      esphome:
        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2026.3.2@sha256:7edfba9d31b11e3852863fca788e3cff729e43e5af68446604aea875e65f684d
            env:
              TZ: "Europe/Amsterdam"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                memory: 512Mi
                cpu: 100m
              limits:
                memory: 2Gi
        pod:
          hostNetwork: true

    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052

    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        rules:
          - backendRefs:
              - name: esphome-app
                port: 6052

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
      cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
