---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app esphome
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: volsync
  path: ./kubernetes/main/apps/home-automation/esphome/app
  postBuild:
    substitute:
      APP: esphome
      VOLSYNC_CLAIM: esphome-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
